# CMP 262 - Week 5, Lab 1
## Introduction to pandas and Exploratory Data Analysis

### Goal
Use pandas to load, inspect, summarize, select, calculate, sort, and filter data from an Excel file. Complete each task in order and run every cell.

## Part 1 - Import pandas and Load the Data

### Example with unrelated data
```python
import pandas as pd
books = pd.read_excel("BookData.xlsx")
```

For this lab, import pandas using the standard alias and load `CampusWorkshopData.xlsx` into a DataFrame named `workshops`.

In [8]:
import pandas as pd
workshops = pd.read_excel("CampusWorkshopData.xlsx")

### Task 1 - Preview the Data
Display the first 5 rows and the last 3 rows of `workshops`.

In [14]:
# Write your code here
workshops.head()
workshops.tail(3)

,Workshop_ID,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended,Satisfaction
9,110,Responsible AI,Artificial Intelligence,Online,2.0,32,27.0,4.6
10,111,Web Development,Programming,In Person,3.0,29,24.0,4.1
11,112,Career Technology Tools,Career Skills,Online,1.5,21,NaN,4.3

### Task 2 - Size and Sample
1. Display the number of rows and columns using `.shape`.
2. Display 4 random rows using `random_state=3` so the same sample appears each time.

In [17]:
# Write your code here
workshops.shape
workshops.sample(4, random_state=3)

,Workshop_ID,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended,Satisfaction
5,106,AI Foundations,Artificial Intelligence,Online,3.0,35,31.0,4.7
4,105,Git and GitHub,Programming,In Person,2.0,20,17.0,4.5
1,102,Excel Essentials,Productivity,Online,1.5,30,25.0,4.2
2,103,Cyber Safety,Cybersecurity,In Person,2.0,28,26.0,4.8

## Part 2 - Understand the DataFrame

### Task 3 - Column Information
Display the column names, the data type of each column, and the full `info()` summary.

In [18]:
# Write your code here
workshops.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Workshop_ID     12 non-null     int64
 1   Workshop        12 non-null     str
 2   Category        12 non-null     str
 3   Delivery_Mode   12 non-null     str
 4   Duration_Hours  12 non-null     float64
 5   Registered      12 non-null     int64
 6   Attended        11 non-null     float64
 7   Satisfaction    11 non-null     float64
dtypes: float64(3), int64(2), str(3)
memory usage: 900.0 bytes

### Task 4 - Series and DataFrame
1. Select the `Workshop` column so the result is a Series.
2. Select the `Workshop` and `Category` columns together so the result is a DataFrame.
3. In a markdown cell, explain the difference you observe.

In [20]:
# Write your code here
workshops["Workshop"]
workshops[["Workshop", "Category"]]

                   Workshop                 Category
0             Python Basics              Programming
1          Excel Essentials             Productivity
2              Cyber Safety            Cybersecurity
3        Data Visualization             Data Science
4            Git and GitHub              Programming
5            AI Foundations  Artificial Intelligence
6                SQL Basics             Data Science
7       Presentation Design             Productivity
8            Network Basics            Cybersecurity
9            Responsible AI  Artificial Intelligence
10          Web Development              Programming
11  Career Technology Tools            Career Skills

Write your explanation here.

## Part 3 - Describe the Data

### Task 5 - Numerical Statistics
For `Attended`, display the mean, median, minimum, and maximum. Then use `describe()` to summarize all numerical columns.

In [22]:
# Write your code here
workshops.iloc[:14]["Attended"].mean()
workshops.iloc[:14]["Attended"].median()
workshops.iloc[:14]["Attended"].min()
workshops.iloc[:14]["Attended"].max()
workshops.describe()

       Workshop_ID  Duration_Hours  Registered   Attended  Satisfaction
count    12.000000       12.000000   12.000000  11.000000     11.000000
mean    106.500000        2.125000   25.833333  22.272727      4.409091
std       3.605551        0.527645    5.149287   4.941476      0.254773
min     101.000000        1.500000   18.000000  14.000000      4.000000
25%     103.750000        1.875000   21.750000  19.000000      4.250000
50%     106.500000        2.000000   25.500000  22.000000      4.400000
75%     109.250000        2.500000   29.250000  25.500000      4.600000
max     112.000000        3.000000   35.000000  31.000000      4.800000

### Task 6 - Categorical Data
1. Display all unique values in `Category`.
2. Count the number of workshops in each category.
3. Count the workshops for each delivery mode.

In [23]:
# Write your code here
workshops["Category"].unique()
workshops["Category"].value_counts()
workshops["Delivery_Mode"].value_counts()

Delivery_Mode
In Person    6
Online       6
Name: count, dtype: int64

## Part 4 - Select Rows and Columns

### Task 7 - Select Columns
Create and display a DataFrame containing only `Workshop`, `Registered`, and `Attended`, in that order.

In [24]:
# Write your code here
workshops[["Workshop","Registered","Attended"]]

                   Workshop  Registered  Attended
0             Python Basics          24      21.0
1          Excel Essentials          30      25.0
2              Cyber Safety          28      26.0
3        Data Visualization          22      18.0
4            Git and GitHub          20      17.0
5            AI Foundations          35      31.0
6                SQL Basics          26      22.0
7       Presentation Design          18      14.0
8            Network Basics          25      20.0
9            Responsible AI          32      27.0
10          Web Development          29      24.0
11  Career Technology Tools          21       NaN

### Task 8 - Select with `.loc[]`
Use `.loc[]` to display rows with index labels 2 through 5 and columns from `Workshop` through `Attended`. Remember that `.loc[]` includes the ending label.

In [ ]:
workshops.loc[2:6, "Workshop":"Attended"]

,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended
2,Cyber Safety,Cybersecurity,In Person,2.0,28,26.0
3,Data Visualization,Data Science,Online,2.5,22,18.0
4,Git and GitHub,Programming,In Person,2.0,20,17.0
5,AI Foundations,Artificial Intelligence,Online,3.0,35,31.0
6,SQL Basics,Data Science,In Person,2.0,26,22.0

### Task 9 - Select with `.iloc[]`
Use `.iloc[]` to display the first 4 rows and the columns in integer positions 1 through 3. Remember that `.iloc[]` excludes the stop position.

In [9]:
workshops.iloc[1:4,0:4]

   Workshop_ID            Workshop       Category Delivery_Mode
1          102    Excel Essentials   Productivity        Online
2          103        Cyber Safety  Cybersecurity     In Person
3          104  Data Visualization   Data Science        Online

### Task 10 - Chain Commands
Using one statement, select the first 5 rows and calculate the mean of `Registered` for those rows.

In [10]:
workshops.iloc[:5]["Registered"].mean()

np.float64(24.8)

## Part 5 - Arithmetic and a New Column

### Task 11 - Attendance Rate
Create a new column named `Attendance_Rate`. Divide `Attended` by `Registered`, multiply by 100, and round the result to one decimal place. Display `Workshop`, `Registered`, `Attended`, and `Attendance_Rate`.

In [14]:
# Write your code here
workshops["Attendence_Rate"] = workshops["Attended"]/workshops["Registered"]*100
workshops[["Workshop","Registered","Attended","Attendence_Rate"]]

                   Workshop  Registered  Attended  Attendence_Rate
0             Python Basics          24      21.0        87.500000
1          Excel Essentials          30      25.0        83.333333
2              Cyber Safety          28      26.0        92.857143
3        Data Visualization          22      18.0        81.818182
4            Git and GitHub          20      17.0        85.000000
5            AI Foundations          35      31.0        88.571429
6                SQL Basics          26      22.0        84.615385
7       Presentation Design          18      14.0        77.777778
8            Network Basics          25      20.0        80.000000
9            Responsible AI          32      27.0        84.375000
10          Web Development          29      24.0        82.758621
11  Career Technology Tools          21       NaN              NaN

## Part 6 - Sort and Filter

### Task 12 - Sort the Data
Create a new DataFrame named `sorted_workshops` by sorting from the highest to the lowest number registered. Display the first 5 rows. Do not change the original DataFrame.

In [15]:
# Write your code here
sorted_workshops= workshops.sort_values("Registered", ascending=False)

### Task 13 - One-Condition Filter
Create a Boolean mask for workshops with a satisfaction score of 4.5 or higher. Use the mask to display the matching rows.

In [17]:
# Write your code here
mask = workshops["Satisfaction"] >= 4.5
workshops[mask]

,Workshop_ID,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended,Satisfaction,Atendence_Rate,Attendence_Rate
0,101,Python Basics,Programming,In Person,2.0,24,21.0,4.6,87.500000,87.500000
2,103,Cyber Safety,Cybersecurity,In Person,2.0,28,26.0,4.8,92.857143,92.857143
4,105,Git and GitHub,Programming,In Person,2.0,20,17.0,4.5,85.000000,85.000000
5,106,AI Foundations,Artificial Intelligence,Online,3.0,35,31.0,4.7,88.571429,88.571429
9,110,Responsible AI,Artificial Intelligence,Online,2.0,32,27.0,4.6,84.375000,84.375000

### Task 14 - Multiple-Condition Filter
Display workshops that are `In Person` **and** have at least 20 attendees. Use parentheses around each comparison and the pandas `&` operator.

In [19]:
# Write your code here
workshops[(workshops["Delivery_Mode"] == "In Person") & (workshops["Attended"] >=20)]

,Workshop_ID,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended,Satisfaction,Atendence_Rate,Attendence_Rate
0,101,Python Basics,Programming,In Person,2.0,24,21.0,4.6,87.500000,87.500000
2,103,Cyber Safety,Cybersecurity,In Person,2.0,28,26.0,4.8,92.857143,92.857143
6,107,SQL Basics,Data Science,In Person,2.0,26,22.0,4.3,84.615385,84.615385
8,109,Network Basics,Cybersecurity,In Person,2.5,25,20.0,NaN,80.000000,80.000000
10,111,Web Development,Programming,In Person,3.0,29,24.0,4.1,82.758621,82.758621

### Task 15 - OR and NOT Filters
1. Display workshops whose category is `Programming` **or** `Data Science`.
2. Display workshops that are **not** online.
Use `|` for OR and `~` for NOT.

In [22]:
# Write your code here
workshops[(workshops["Category"] == "Programming") | (workshops["Category"] == "Data Science")]
workshops[~(workshops["Delivery_Mode"] == "Online")]

,Workshop_ID,Workshop,Category,Delivery_Mode,Duration_Hours,Registered,Attended,Satisfaction,Atendence_Rate,Attendence_Rate
0,101,Python Basics,Programming,In Person,2.0,24,21.0,4.6,87.500000,87.500000
2,103,Cyber Safety,Cybersecurity,In Person,2.0,28,26.0,4.8,92.857143,92.857143
4,105,Git and GitHub,Programming,In Person,2.0,20,17.0,4.5,85.000000,85.000000
6,107,SQL Basics,Data Science,In Person,2.0,26,22.0,4.3,84.615385,84.615385
8,109,Network Basics,Cybersecurity,In Person,2.5,25,20.0,NaN,80.000000,80.000000
10,111,Web Development,Programming,In Person,3.0,29,24.0,4.1,82.758621,82.758621

## Part 7 - Final EDA Challenge

Use pandas to answer this question: **Which delivery mode has the higher average satisfaction score?**

1. Calculate the average `Satisfaction` separately for `Online` and `In Person` workshops.
2. Display both averages.
3. In the markdown cell below, write 2-3 sentences explaining your conclusion and mention the values that support it.

In [31]:
# Write your code here
online_avg = workshops[workshops["Delivery_Mode"] == "Online"]["Satisfaction"].mean()
Inperson_avg = workshops[workshops["Delivery_Mode"] == "In Person"]["Satisfaction"].mean()
print("Online Satifaction average:",online_avg)
print("In Person Satisfaction average:",Inperson_avg)

Online Satifaction average: 4.366666666666666
In Person Satisfaction average: 4.459999999999999

3. On an average, the satisfaction of people online was lower than the satifaction of the people who ordered in person by a ~0.5 rating.

Write your conclusion here.

## Reflection
Answer in 3-4 sentences:

1. What is one difference between a pandas Series and a DataFrame?
2. When would you use `.loc[]` instead of `.iloc[]`?
3. What is one useful fact you discovered in the dataset?

Write your reflection here.

1. A DataFrame is a two dimensional table with both rows and columns, whereas a panda Series is a one dimensional labeled data with only one column.
2. We use .loc[] selects labeled rows and columns whereas iloc.[] selects rows and columns by position.
3. The ability to combine two cells together to find an averages of both while using the mean functions.